import {
  Camera,
  Clock,
  Entity,
  EntityManager,
  Globe,
  ImageryLayer,
  LayerManager,
  ModelManager,
  PointGraphics,
  PolygonGraphics,
  PolylineGraphics,
  SymbolGraphics,
  IconGraphics,
  TextGraphics,
  Scene,
  SceneTilesetCollection,
  AtmosphereLightingMode,
  DebugSettingsPanel,
  Timeline,
  SpringControl,
  Terrain,
  TelluxGlobeControls,
  preloadFontMsdfAtlas,
  setMsdfAtlasForFont,
  disposeGlyphAtlases,
  loadMsdfAtlas,
  disposeMsdfAtlas,
  telluxConfig,
  Viewer,
  ViewerRenderer
} from './Viewer'
import { RTCAutoUniforms } from './rendering/RTCAutoUniforms'
import {
  applyRTCInstancing,
  setRTCMatrixAt
} from './rendering/applyRTCInstancing'

export { RTCAutoUniforms, applyRTCInstancing, setRTCMatrixAt }
export type {
  ClockChangeEvent,
  ClockChangeReason,
  ClockEventListener,
  ClockEventMap,
  ClockOptions,
  ClockTickEvent,
  DateTimeInput
} from './Clock'

export {
  Camera,
  Clock,
  Entity,
  EntityManager,
  Globe,
  HismManager,
  HighlightManager,
  ImageryLayer,
  LayerManager,
  ModelManager,
  PointGraphics,
  PolygonGraphics,
  PolylineGraphics,
  SymbolGraphics,
  IconGraphics,
  TextGraphics,
  preloadFontMsdfAtlas,
  setMsdfAtlasForFont,
  disposeGlyphAtlases,
  loadMsdfAtlas,
  disposeMsdfAtlas,
  PositionPipeline,
  Scene,
  SceneTilesetCollection,
  HismCluster,
  HismPickMarker,
  collectHismRuntimeStats,
  createInstancedVegetationPipeline,
  createRTCPositionPipeline,
  createRTCPositionStage,
  createWindSwayLeavesMaterial,
  createWindSwayStage,
  createWindSwayUniforms,
  hasTelluxPositionPipeline,
  AtmosphereLightingMode,
  DEFAULT_POINT_CLOUD_SHADING,
  resolvePointCloudShading,
  DebugSettingsPanel,
  Timeline,
  SpringControl,
  Terrain,
  TelluxGlobeControls,
  Viewer,
  ViewerRenderer,
  type CameraEllipsoid,
  type CameraEllipsoidProvider,
  type CameraFlyToDestination,
  type CameraFlyToOptions,
  type CameraFlightEasingFunction,
  type CameraOrientation,
  type CameraSetViewOptions,
  type AddHismLayerOptions,
  type AddModelOptions,
  type CloudQualityPreset,
  type CloudShadowQuality,
  type LensFlareQuality,
  type DebugSettingsPanelOptions,
  type TimelineOptions,
  type CartographicCoordinateTuple,
  type CartographicCoordinates,
  type CartographicFrameOptions,
  type CartographicInput,
  type CesiumIon3DTilesetOptions,
  type CesiumIonImagerySourceOptions,
  type CesiumIonTerrainOptions,
  type TiandituTerrainOptions,
  type ColorInput,
  type EntityOptions,
  type PointOptions,
  type PolylineOptions,
  type PolygonOptions,
  type SymbolOptions,
  type IconOptions,
  type TextOptions,
  type SymbolAnchor,
  type SymbolTextRelative,
  type GlyphTextConfig,
  type GlyphTextRun,
  type MsdfAtlas,
  type MsdfAtlasData,
  type MsdfGlyphMetrics,
  type FlyToTargetOffset,
  type FlyToTargetOptions,
  type FlyToTargetTarget,
  type GeoJSONData,
  type GeoJSONFeature,
  type GeoJSONFeatureCollection,
  type GeoJSONFeatureProperties,
  type GeoJSONFeatureStyle,
  type GeoJSONGeometry,
  type GeoJSONGetStyleCallback,
  type GeoJSONImagerySourceOptions,
  type GltfModelLightingMode,
  type GltfModelMaterialMode,
  type GltfModelOptions,
  type HismArchetype,
  type HismInstancePlacement,
  type HismLayer,
  type HismMeshPart,
  type HismLodLevel,
  type HismPickResult,
  type HighlightTarget,
  type ViewerHighlightOptions,
  type ViewerHighlightOutlineOptions,
  type ViewerHighlightOverlayOptions,
  type HismRuntimeStats,
  type HismLayerRuntimeStats,
  type HismManagerOptions,
  type HismApplyInstanceMatrix,
  type PositionPipelineApplyOptions,
  type PositionPipelineComposeOptions,
  type PositionPipelineStage,
  type PositionPipelineStageContext,
  type WindSwayLeavesMaterialOptions,
  type WindSwayUniformValues,
  type ImageryLayerOptions,
  type ImageryLayerSourceOptions,
  type ImageryLayerStyleOptions,
  type Load3DTilesetOptions,
  type ModelLayer,
  type MVTImagerySourceOptions,
  type MVTFeatureProperties,
  type MVTFeatureStyle,
  type MVTGetStyleCallback,
  type Picked3DTilesFeature,
  type PickedObject,
  type PickObjectOptions,
  type PickEntityOptions,
  type PickedEntity,
  type ScreenPosition,
  type SampleHeightMostDetailedOptions,
  type SampleHeightMostDetailedResult,
  type SampleHeightOptions,
  type SurfaceMaterialMode,
  type ViewerSurfaceMaterialOptions,
  type SpringControlOptions,
  type TerrainRenderOptions,
  type TerrainOptions,
  type TerrainTileLoadingOptions,
  type Scene3DTileLoadingOptions,
  type ThreeDTilesRenderOptions,
  type PointCloudShadingOptions,
  type ResolvedPointCloudShading,
  type TelluxConfig,
  type TilesetFeatureProperties,
  type TilesetLayer,
  type Url3DTilesetOptions,
  type UrlTerrainOptions,
  type EntityTransparencyMode,
  type HeightSamplingSource,
  type ViewerClickEvent,
  type ViewerEvent,
  type ViewerEventListener,
  type ViewerEventMap,
  type ViewerEntityOptions,
  type ViewerEntityTransparencyOptions,
  type ViewerMouseEvent,
  type ViewerMouseMoveEvent,
  type ViewerPickLayer,
  type ViewerPickOptions,
  type ViewerPickResult,
  type ViewerRendererOptions,
  type ViewerRendererType,
  type ViewerControls,
  type ViewerAtmosphereLightingOptions,
  type ViewerAtmospherePhotometricOptions,
  type ViewerAtmosphereNightOptions,
  type ViewerAtmosphereOptions,
  type ViewerAtmosphereScatteringOptions,
  type ViewerAtmosphereShadowOptions,
  type ViewerAtmosphereSkyOptions,
  type ViewerAtmosphereStarsOptions,
  type ViewerAutoExposureOptions,
  type ViewerBloomOptions,
  type ViewerCloudLayerOptions,
  type ViewerCloudLookOptions,
  type ViewerCloudOptions,
  type ViewerCloudShadowOptions,
  type ViewerFallbackAmbientLightOptions,
  type ViewerLensFlareOptions,
  type ViewerLensFlareThresholdOptions,
  type ViewerPostProcessOptions,
  type ViewerPostProcessStageOptions,
  type ViewerSceneOptions,
  type ViewerSurfaceOptions,
  type ViewerWidgetOptions,
  type ViewerOptions,
  type TelluxRenderer,
  type TelluxWebGLRenderer,
  type TelluxWebGPURenderer,
  type WMSImagerySourceOptions,
  type WMTSImagerySourceOptions,
  type WMTSTileMatrix,
  type XYZImagerySourceOptions
} from './Viewer'
export { telluxAssetFileNames, telluxAssetUrls, type TelluxAssetName } from './assets'

/**
 * Tellux 库入口对象。
 *
 * Tellux library entry object.
 */
const tellux = {
  Viewer,
  Scene,
  AtmosphereLightingMode,
  Camera,
  Clock,
  ImageryLayer,
  LayerManager,
  ModelManager,
  Globe,
  Terrain,
  ViewerRenderer,
  DebugSettingsPanel,
  Timeline,
  SpringControl,
  RTCAutoUniforms,
  applyRTCInstancing,
  setRTCMatrixAt,
  preloadFontMsdfAtlas,
  setMsdfAtlasForFont,
  disposeGlyphAtlases,
  loadMsdfAtlas,
  disposeMsdfAtlas,

  /**
   * Tellux 静态资源父级目录。
   *
   * Parent directory for Tellux static assets.
   */
  get baseUrl() {
    return telluxConfig.baseUrl
  },

  set baseUrl(value: string) {
    telluxConfig.baseUrl = value
  }
}

export { tellux }
export default tellux
